# Form implementation generated from reading ui file 'ui/account_page.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Account_Form(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1237, 859)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        MainWindow.setStyleSheet("background-color:rgb(54, 57, 76);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QFrame, QPushButton{\n"
"border:none;}\n"
"QPushButton:hover{text-decoration:underline}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 500))
        self.frame.setMaximumSize(QtCore.QSize(250, 500))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_7.setStyleSheet("background:transparent;\n"
"color:white;\n"
"font-size:32px;\n"
"padding-left:4%;\n"
"text-align:left;\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout.addWidget(self.pushButton_7)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_5.setStyleSheet("background:transparent;\n"
"word-break:break-word;\n"
"color:white;\n"
"font-size:30px;\n"
"padding-left:4%;\n"
"text-align:left;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_6.setStyleSheet("background:transparent;\n"
"word-break:break-word;\n"
"color:white;\n"
"font-size:30px;\n"
"padding-left:4%;\n"
"text-align:left;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(500, 800))
        self.frame_2.setMaximumSize(QtCore.QSize(800, 1500))
        self.frame_2.setStyleSheet("background:transparent;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setGeometry(QtCore.QRect(30, 0, 471, 91))
        self.label.setStyleSheet("background:transparent;\n"
"color:white;\n"
"font-size:32px;\n"
"padding-left:4%;\n"
"text-align:left;\n"
"")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(140, 650, 231, 71))
        self.pushButton.setStyleSheet("background-color:rgb(74, 113, 255);\n"
"word-break:break-word;\n"
"color:white;\n"
"font-size:27px;\n"
"padding-left:4%;\n"
"text-align:center;")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(150, 400, 221, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(500, 800))
        self.frame_3.setMaximumSize(QtCore.QSize(800, 1500))
        self.frame_3.setStyleSheet("background:transparent;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(-10, 0, 471, 91))
        self.label_3.setStyleSheet("background:transparent;\n"
"color:white;\n"
"font-size:32px;\n"
"padding-left:4%;\n"
"text-align:left;\n"
"")
        self.label_3.setObjectName("label_3")
        self.overalllprogressBar = QtWidgets.QProgressBar(parent=self.frame_3)
        self.overalllprogressBar.setGeometry(QtCore.QRect(310, 670, 171, 31))
        self.overalllprogressBar.setStyleSheet("color:white;")
        self.overalllprogressBar.setProperty("value", 24)
        self.overalllprogressBar.setObjectName("overalllprogressBar")
        self.physprogressBar_2 = QtWidgets.QProgressBar(parent=self.frame_3)
        self.physprogressBar_2.setGeometry(QtCore.QRect(320, 250, 171, 31))
        self.physprogressBar_2.setStyleSheet("color:white;")
        self.physprogressBar_2.setProperty("value", 24)
        self.physprogressBar_2.setObjectName("physprogressBar_2")
        self.mathsprogressBar_3 = QtWidgets.QProgressBar(parent=self.frame_3)
        self.mathsprogressBar_3.setGeometry(QtCore.QRect(320, 140, 171, 31))
        self.mathsprogressBar_3.setStyleSheet("color:white;")
        self.mathsprogressBar_3.setProperty("value", 24)
        self.mathsprogressBar_3.setObjectName("mathsprogressBar_3")
        self.bioprogressBar_4 = QtWidgets.QProgressBar(parent=self.frame_3)
        self.bioprogressBar_4.setGeometry(QtCore.QRect(320, 360, 171, 31))
        self.bioprogressBar_4.setStyleSheet("color:white;")
        self.bioprogressBar_4.setProperty("value", 24)
        self.bioprogressBar_4.setObjectName("bioprogressBar_4")
        self.chemprogressBar_5 = QtWidgets.QProgressBar(parent=self.frame_3)
        self.chemprogressBar_5.setGeometry(QtCore.QRect(320, 470, 171, 31))
        self.chemprogressBar_5.setStyleSheet("color:white;")
        self.chemprogressBar_5.setProperty("value", 24)
        self.chemprogressBar_5.setObjectName("chemprogressBar_5")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(-10, 120, 191, 51))
        self.label_2.setStyleSheet("background:transparent;\n"
"color:white;\n"
"font-size:29px;\n"
"padding-left:4%;\n"
"text-align:left;\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(-10, 250, 151, 51))
        self.label_4.setStyleSheet("background:transparent;\n"
"color:white;\n"
"font-size:29px;\n"
"padding-left:4%;\n"
"text-align:left;\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(-10, 350, 151, 51))
        self.label_5.setStyleSheet("background:transparent;\n"
"color:white;\n"
"font-size:29px;\n"
"padding-left:4%;\n"
"text-align:left;\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(0, 460, 151, 51))
        self.label_6.setStyleSheet("background:transparent;\n"
"color:white;\n"
"font-size:29px;\n"
"padding-left:4%;\n"
"text-align:left;\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(0, 660, 151, 51))
        self.label_7.setStyleSheet("background:transparent;\n"
"color:white;\n"
"font-size:29px;\n"
"padding-left:4%;\n"
"text-align:left;\n"
"")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1237, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_7.setText(_translate("MainWindow", "Главная"))
        self.pushButton_5.setText(_translate("MainWindow", "Мой аккаунт"))
        self.pushButton_6.setText(_translate("MainWindow", "Настройки"))
        self.label.setText(_translate("MainWindow", "Информация об аккаунте"))
        self.pushButton.setText(_translate("MainWindow", "Сохранить!"))
        self.label_3.setText(_translate("MainWindow", "Информация об успеваемости"))
        self.label_2.setText(_translate("MainWindow", "Математика"))
        self.label_4.setText(_translate("MainWindow", "Физика"))
        self.label_5.setText(_translate("MainWindow", "Биология"))
        self.label_6.setText(_translate("MainWindow", "Химия"))
        self.label_7.setText(_translate("MainWindow", "Общий"))
