# Form implementation generated from reading ui file 'math_page.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_Math(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1259, 809)
        Form.setStyleSheet("background:rgb(54, 57, 76);")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(450, 10, 281, 101))
        self.label.setStyleSheet("color:white;\n"
"font-size:40px;\n"
"text-align:center;")
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(parent=Form)
        self.comboBox.setGeometry(QtCore.QRect(460, 180, 341, 61))
        self.comboBox.setStyleSheet("color:white;\n"
"font-size:20px;\n"
"background:rgb(110, 127, 158) ;\n"
"border-radius:10px;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(parent=Form)
        self.comboBox_2.setGeometry(QtCore.QRect(460, 340, 341, 61))
        self.comboBox_2.setStyleSheet("color:white;\n"
"font-size:20px;\n"
"background:rgb(110, 127, 158) ;\n"
"border-radius:10px;")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(parent=Form)
        self.comboBox_3.setGeometry(QtCore.QRect(460, 500, 341, 61))
        self.comboBox_3.setStyleSheet("color:white;\n"
"font-size:20px;\n"
"background:rgb(110, 127, 158) ;\n"
"border-radius:10px;")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.progressBar = QtWidgets.QProgressBar(parent=Form)
        self.progressBar.setGeometry(QtCore.QRect(860, 200, 118, 23))
        self.progressBar.setStyleSheet("color:white;")
        self.progressBar.setProperty("value", 33)
        self.progressBar.setObjectName("progressBar")
        self.progressBar_2 = QtWidgets.QProgressBar(parent=Form)
        self.progressBar_2.setGeometry(QtCore.QRect(860, 360, 118, 23))
        self.progressBar_2.setStyleSheet("color:white\n"
";")
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.progressBar_3 = QtWidgets.QProgressBar(parent=Form)
        self.progressBar_3.setGeometry(QtCore.QRect(860, 520, 118, 23))
        self.progressBar_3.setStyleSheet("color:white;")
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setObjectName("progressBar_3")
        self.pushButton_7 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 190, 211, 111))
        self.pushButton_7.setStyleSheet("background:transparent;\n"
"text-decoration:underline;\n"
"color:white;\n"
"font-size:32px;\n"
"padding-left:4%;\n"
"text-align:left;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.settings_btn = QtWidgets.QPushButton(parent=Form)
        self.settings_btn.setGeometry(QtCore.QRect(20, 440, 211, 101))
        self.settings_btn.setStyleSheet("background:transparent;\n"
"word-break:break-word;\n"
"color:white;\n"
"font-size:30px;\n"
"padding-left:4%;\n"
"text-align:left;")
        self.settings_btn.setObjectName("settings_btn")
        self.btn_to_account = QtWidgets.QPushButton(parent=Form)
        self.btn_to_account.setGeometry(QtCore.QRect(20, 320, 211, 111))
        self.btn_to_account.setStyleSheet("background:transparent;\n"
"word-break:break-word;\n"
"color:white;\n"
"font-size:30px;\n"
"padding-left:4%;\n"
"text-align:left;")
        self.btn_to_account.setObjectName("btn_to_account")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Математика"))
        self.comboBox.setItemText(0, _translate("Form", "Алгебра"))
        self.comboBox.setItemText(1, _translate("Form", "Решение квадратных уравнений"))
        self.comboBox.setItemText(2, _translate("Form", "Тождественные преобразование"))
        self.comboBox.setItemText(3, _translate("Form", "Решение биквадратных уравнений"))
        self.comboBox.setItemText(4, _translate("Form", "Неравенства.Свойства неравенств"))
        self.comboBox_2.setItemText(0, _translate("Form", "Планиметрия"))
        self.comboBox_3.setItemText(0, _translate("Form", "Теория вероятностей"))
        self.pushButton_7.setText(_translate("Form", "Главная"))
        self.settings_btn.setText(_translate("Form", "Настройки"))
        self.btn_to_account.setText(_translate("Form", "Перейти в \n"
"свой аккаунт"))
