# Form implementation generated from reading ui file 'ui/settings_pageUI.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_Settings(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1073, 818)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        MainWindow.setStyleSheet("background-color:rgb(54, 57, 76);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QFrame, QPushButton{\n"
"border:none;}\n"
"QPushButton:hover{text-decoration:underline}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 500))
        self.frame.setMaximumSize(QtCore.QSize(250, 1000))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo = QtWidgets.QLabel(parent=self.frame)
        self.logo.setMaximumSize(QtCore.QSize(144, 144))
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.verticalLayout.addWidget(self.logo)
        self.ToMain = QtWidgets.QPushButton(parent=self.frame)
        self.ToMain.setStyleSheet("background:transparent;\n"
"color:white;\n"
"font-size:32px;\n"
"padding-left:4%;\n"
"text-align:left;\n"
"")
        self.ToMain.setObjectName("ToMain")
        self.verticalLayout.addWidget(self.ToMain)
        self.ToAccount = QtWidgets.QPushButton(parent=self.frame)
        self.ToAccount.setStyleSheet("background:transparent;\n"
"word-break:break-word;\n"
"color:white;\n"
"font-size:30px;\n"
"padding-left:4%;\n"
"text-align:left;")
        self.ToAccount.setObjectName("ToAccount")
        self.verticalLayout.addWidget(self.ToAccount)
        self.ToSettings = QtWidgets.QPushButton(parent=self.frame)
        self.ToSettings.setStyleSheet("background:transparent;\n"
"word-break:break-word;\n"
"color:white;\n"
"font-size:30px;\n"
"padding-left:4%;\n"
"text-align:left;\n"
"text-decoration:underline;")
        self.ToSettings.setObjectName("ToSettings")
        self.verticalLayout.addWidget(self.ToSettings)
        self.horizontalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(500, 800))
        self.frame_3.setMaximumSize(QtCore.QSize(800, 1500))
        self.frame_3.setStyleSheet("background:transparent;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.text_size = QtWidgets.QSpinBox(parent=self.frame_3)
        self.text_size.setGeometry(QtCore.QRect(350, 120, 111, 31))
        self.text_size.setStyleSheet("font-size:18px;")
        self.text_size.setObjectName("text_size")
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setGeometry(QtCore.QRect(60, 110, 271, 51))
        self.label.setStyleSheet("background:transparent;\n"
"color:white;\n"
"font-size:20px;\n"
"padding-left:4%;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 191, 51))
        self.label_2.setStyleSheet("background:transparent;\n"
"color:white;\n"
"font-size:32px;\n"
"padding-left:4%;\n"
"text-align:left;\n"
"")
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.frame_3)
        self.textBrowser.setGeometry(QtCore.QRect(30, 640, 201, 161))
        self.textBrowser.setStyleSheet("color:white;\n"
"font-size:20px;")
        self.textBrowser.setObjectName("textBrowser")
        self.login_again = QtWidgets.QPushButton(parent=self.frame_3)
        self.login_again.setGeometry(QtCore.QRect(310, 680, 291, 41))
        self.login_again.setStyleSheet("color:rgb(132, 153, 189);\n"
"font-size:23px;\n"
"text-align:left;")
        self.login_again.setObjectName("login_again")
        self.nickname = QtWidgets.QLabel(parent=self.frame_3)
        self.nickname.setGeometry(QtCore.QRect(310, 630, 291, 41))
        self.nickname.setStyleSheet("color:rgb(132, 153, 189);\n"
"font-size:23px;")
        self.nickname.setText("")
        self.nickname.setObjectName("nickname")
        self.horizontalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ToMain.setText(_translate("MainWindow", "Главная"))
        self.ToAccount.setText(_translate("MainWindow", "Мой аккаунт"))
        self.ToSettings.setText(_translate("MainWindow", "Настройки"))
        self.label.setText(_translate("MainWindow", "Изменить размер шрифта \n"
"в параграфе"))
        self.label_2.setText(_translate("MainWindow", "Параметры"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:20px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://github.com/NotAKes/frog.study\"><span style=\" font-size:18pt; text-decoration: underline; color:#8499bd;\">Github</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; text-decoration: underline; color:#8499bd;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://github.com/NotAKes/frog.study/issues\"><span style=\" font-size:18pt; text-decoration: underline; color:#8499bd;\">Нашли ошибку?</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; text-decoration: underline; color:#8499bd;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20px; color:#8499bd;\">v0.34 @notakes</span></p></body></html>"))
        self.login_again.setText(_translate("MainWindow", "Войти в другой аккаунт?"))
