# Form implementation generated from reading ui file 'ui/edit_page.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_Edit(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(733, 710)
        Form.setStyleSheet("QWidget{background:rgb(54, 57, 76);}\n"
"QPushButton{color:white;\n"
"background:transparent;\n"
"font-size:20px;}\n"
"QPushButton:hover{\n"
"text-decoration:underline;}\n"
"QScrollArea{border:1px solid  rgb(231, 251, 255);}")
        self.senders_text = QtWidgets.QTextEdit(parent=Form)
        self.senders_text.setGeometry(QtCore.QRect(70, 180, 561, 421))
        self.senders_text.setStyleSheet("color:white;\n"
"font-size:25px;\n"
"background:rgb(117, 126, 168);\n"
"border: 2px solid rgb(52, 56, 75);")
        self.senders_text.setObjectName("senders_text")
        self.send_button = QtWidgets.QPushButton(parent=Form)
        self.send_button.setGeometry(QtCore.QRect(150, 90, 361, 41))
        self.send_button.setStyleSheet("QPushButton{background-color :rgb(110, 127, 158);\n"
"color:white;\n"
"font-size:25px;\n"
"padding-left:20%;\n"
"text-align:center;\n"
"border-radius: 10px;}\n"
"QPushButton:hover{\n"
"background-color :rgb(128, 149, 184);}")
        self.send_button.setObjectName("send_button")
        self.title_edit = QtWidgets.QLineEdit(parent=Form)
        self.title_edit.setGeometry(QtCore.QRect(130, 30, 411, 41))
        self.title_edit.setStyleSheet("color:white;\n"
"font-size:25px;\n"
"background:rgb(117, 126, 168);\n"
"border: 2px solid rgb(52, 56, 75);")
        self.title_edit.setObjectName("title_edit")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(300, 140, 101, 31))
        self.label_3.setStyleSheet("QLabel{\n"
"color:white;\n"
"font-size:25px;\n"
"padding-left:20%;\n"
"text-align:center;\n"
"border-radius: 10px;}")
        self.label_3.setObjectName("label_3")
        self.confirm_send = QtWidgets.QPushButton(parent=Form)
        self.confirm_send.setGeometry(QtCore.QRect(510, 630, 171, 51))
        self.confirm_send.setStyleSheet("QPushButton{background-color :rgb(110, 127, 158);\n"
"color:white;\n"
"font-size:25px;\n"
"padding-left:20%;\n"
"text-align:left;\n"
"border-radius: 10px;}\n"
"QPushButton:hover{\n"
"background-color :rgb(128, 149, 184);}")
        self.confirm_send.setObjectName("confirm_send")
        self.error_label = QtWidgets.QLabel(parent=Form)
        self.error_label.setGeometry(QtCore.QRect(50, 630, 181, 51))
        self.error_label.setStyleSheet("color:orange;\n"
"font-size:19px;\n"
"text-align: justify;\n"
"justify-content: center;")
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.goback = QtWidgets.QPushButton(parent=Form)
        self.goback.setGeometry(QtCore.QRect(20, 40, 51, 51))
        self.goback.setMaximumSize(QtCore.QSize(60, 16777215))
        self.goback.setText("")
        self.goback.setObjectName("goback")
        self.success_label = QtWidgets.QLabel(parent=Form)
        self.success_label.setGeometry(QtCore.QRect(270, 630, 231, 51))
        self.success_label.setStyleSheet("color:rgb(145, 255, 143);\n"
"font-size:22px;\n"
"text-align: justify;\n"
"justify-content: center;")
        self.success_label.setText("")
        self.success_label.setObjectName("success_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.senders_text.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:25px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.send_button.setText(_translate("Form", "Загрузить файл"))
        self.label_3.setText(_translate("Form", "ИЛИ"))
        self.confirm_send.setText(_translate("Form", "Изменить"))
